train:
  repetitions: 5
  disp: True
  t_max: 5
  learning_rate: 0.0007
  device: cuda
  rate: 20
  actuator_rate: 60
  total_timesteps: 25_000
  delay_low: 0.03  # absolute delay in seconds
  delay_high: 0.04  # absolute delay in seconds

settings:
  gym_baseline:
      engine: gym
      extend: false
      name: gym
  gym_domain_randomization:
      engine: gym
      extend: false
      domain_randomization: True
      name: gym + DR
  ode_baseline:
      engine: ode
      name: ode
  ode_domain_randomization:
      engine: ode
      domain_randomization: True
      name: ode + DR
  ode_delay:
      engine: ode
      delay: True
      name: ode + DS
  ode_domain_randomization_delay:
      engine: ode
      domain_randomization: True
      delay: True
      name: ode + DR + DS