train:
  repetitions: 5
  disp: True
  t_max: 5
  learning_rate: 0.0007
  device: cuda
  rate: 20
  actuator_rate: 60
  total_timesteps: 10_000
  delay_low: 0. # absolute delay in seconds
  delay_high: 0.04  # absolute delay in seconds

settings:
  gym_baseline:
    engine: gym
  gym_domain_randomization:
      engine: gym
      domain_randomization: True
  gym_delay:
      engine: gym
      delay: True
  gym_domain_randomization_delay:
      engine: gym
      domain_randomization: True
      delay: True
  ode_baseline:
      actuator_rate: 60
      engine: ode
  ode_domain_randomization:
      engine: ode
      domain_randomization: True
  ode_delay:
      engine: ode
      delay: True
  ode_domain_randomization_delay:
      engine: ode
      domain_randomization: True
      delay: True
